// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrN0fzWqiY_X907mV1njMk73zu3oOIevQ',
    appId: '1:955045208943:web:75948c64fe8e0dd7ea3e9a',
    messagingSenderId: '955045208943',
    projectId: 'ali-optical',
    authDomain: 'ali-optical.firebaseapp.com',
    storageBucket: 'ali-optical.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNBHiBhcYwtE-9a_I-p5th_bh05DNF4vM',
    appId: '1:955045208943:android:5cc354c6c408e4d9ea3e9a',
    messagingSenderId: '955045208943',
    projectId: 'ali-optical',
    storageBucket: 'ali-optical.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWpBcC7nS_W1f81jX32IQ3jOSlPPn-jNU',
    appId: '1:955045208943:ios:cde592d1f8e61437ea3e9a',
    messagingSenderId: '955045208943',
    projectId: 'ali-optical',
    storageBucket: 'ali-optical.firebasestorage.app',
    iosClientId: '955045208943-9b94qjojq3mnr6sfhodrs8dsbaesktvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.alioptical',
  );
}
